### PR TITLE
[FIX] Update Filter

### LINKED ISSUE #35: [FIX] Update Filter
- [x] Make adaptive

- Mobile size: 
image
- Laptop size: 
image
- Desktop size: 
image

- [x] Fix qwery-params

### PR DESCRIPTION
**Pull request by JohnGlod**
- [x] Make adaptive

- Mobile size: 
image
- Laptop size: 
image
- Desktop size: 
image

- [x] Fix qwery-params
- query-params do not overwrite each other

- [x]  Added filtering by price and quantity in stock

### CODE REVIEW

File: src/components/Store/StoreContainer.tsx [hunk 1]
```diff
@@ -33,9 +33,17 @@ export const StoreContainer = () => {
...
+    price: searchParams.get('price') || '',
   };
 
+  /*   const searchNameParam = searchParams.get('name');
+  const searchBrandParam = searchParams.get('brand');
+  const searchCategoryParam = searchParams.get('category');
+  const searchDescrParam = searchParams.get('descr');
+  const searchRatingParam = searchParams.get('rating');
+  const searchStockParam = searchParams.get('stock'); */
+
```
Comment (olgakharkevich) [inline src/components/Store/StoreContainer.tsx:46]: Is it necessary or you can remove it?

File: src/components/Store/StoreContainer.tsx [hunk 2]
```diff
@@ -76,35 +84,38 @@ export const StoreContainer = () => {
...
 
-  useEffect(() => {
+  /*   useEffect(() => {
     setBrands(getFilters(correntItems, 'brand'));
     setCategories(getFilters(correntItems, 'category'));
     setPrice(getFiltersRange(correntItems, 'price'));
     setStock(getFiltersRange(correntItems, 'stock'));
   }, [itemOffset, limit, searchParams]);
-
+ */
```
Comment (olgakharkevich) [inline src/components/Store/StoreContainer.tsx:118]: the same question)

**Review by olgakharkevich — COMMENTED** [review]
Great job 👍 thanks a lot)
only small questions about commented code

File: src/components/Store/StoreContainer.tsx (hunk 1 above)
Comment (JohnGlod) [reply src/components/Store/StoreContainer.tsx:46]: > Is it necessary or you can remove it?

I don't think we'll need it in the future. Our data is localized in the application itself, that is, after changing these parameters, we do not need to make a request to the server again with the parameters already changed in the Url request.

File: src/components/Store/StoreContainer.tsx (hunk 2 above)
Comment (JohnGlod) [reply src/components/Store/StoreContainer.tsx:118]: Yes, I think this can also be removed, you just need to finally figure out the filters (I already marked the task on the board) and for now it seems to me that the approach will be the same, but this is not certain.

**Review by olgakharkevich — APPROVED** [review]
Thanks 👍 LGTM)
